name: Philosophy
favicon: null
layout_spectrum: 0.7268880906049162
typography_spectrum: 0.4236175939440727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.910468558780849
  lightness: 0.9797508006449789
  saturation: 0.9757734779268503
  rhythmicContrast: 0.5008934512734413
purpose: []
